### ISSUE TITLE
Error 0x800106EF on Enroll

### ISSUE THREAD

**Issue by ploebb** [resilar/HotFinger#6]
Hey. I run into the following issue with my USB fingerprint reader. The inbuilt (Synaptics) one seems to work fine with your software.

Install works fine, but when I try to enroll a command, it shows error code 0x800106EF

![deviceListing](https://user-images.githubusercontent.com/5870131/76296950-4e467900-62b7-11ea-891b-5eb2497c8cc4.png)

![enrollError](https://user-images.githubusercontent.com/5870131/76296930-45ee3e00-62b7-11ea-9c7b-62c127e0bfb5.png)

My guess is, this reader is just "not compatible"? It works natively with Windows Hello, so my guess was, that it is in fact "WBF-compatible".

I'ts this one: https://acekool.net/products/fingerprint-reader-hub-with-type-c-wire-and-3usb-port
and I did not install any additional software from the manufacturer.

**Comment by resilar** [comment]
Sensor capabilities `0x00000001` is most likely the problem.
```
WINBIO_CAPABILITY_SENSOR         = 00000001h
WINBIO_CAPABILITY_MATCHING       = 00000002h
WINBIO_CAPABILITY_DATABASE       = 00000004h
WINBIO_CAPABILITY_PROCESSING     = 00000008h
WINBIO_CAPABILITY_ENCRYPTION     = 00000010h
WINBIO_CAPABILITY_NAVIGATION     = 00000020h
WINBIO_CAPABILITY_INDICATOR      = 00000040h
WINBIO_CAPABILITY_VIRTUAL_SENSOR = 00000080h
```

HotFinger requires at least `WINBIO_CAPABILITY_DATABASE` (`0x00000004`) for storing enrollments into a private enrollment database. So basically your fingerprint reader is unsupported, sorry.
